---

name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    container: deividrodriguez/byebug:${{ matrix.version }}-${{ matrix.compiler }}

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        version: [2.5.7, 2.6.5, 2.7.0, head]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v2

      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake

      - name: Set ENV for codeclimate (pull_request)
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          echo "::set-env name=GIT_BRANCH::$GITHUB_HEAD_REF"
          echo "::set-env name=GIT_COMMIT_SHA::$(git rev-parse origin/$GITHUB_HEAD_REF)"
        if: github.event_name == 'pull_request'

      - name: Set ENV for codeclimate (push)
        run: |
          echo "::set-env name=GIT_BRANCH::$GITHUB_REF"
          echo "::set-env name=GIT_COMMIT_SHA::$GITHUB_SHA"
        if: github.event_name == 'push'

      - name: Save coverage
        run: cc-test-reporter format-coverage --output coverage/codeclimate.${{ matrix.version }}-${{ matrix.compiler }}.json

      - uses: actions/upload-artifact@v1
        with:
          name: coverage-${{ matrix.version }}-${{ matrix.compiler }}
          path: coverage/codeclimate.${{ matrix.version }}-${{ matrix.compiler }}.json

    timeout-minutes: 15

  coverage:
    container: deividrodriguez/byebug:2.7.0-gcc

    runs-on: ubuntu-18.04

    env:
      CC_TEST_REPORTER_ID: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408

    needs: test

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: coverage-2.5.7-clang
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-2.5.7-gcc
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-2.6.5-clang
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-2.6.5-gcc
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-2.7.0-clang
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-2.7.0-gcc
          path: coverage

      - name: Aggregate & upload results to Code Climate
        run: |
          cc-test-reporter sum-coverage coverage/codeclimate.*.json
          cc-test-reporter upload-coverage
