name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '9.9.x', '2.6.x', '2.5.x', '2.4.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Load Ruby, update gcc
        uses: MSP-Greg/actions-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          base: update
      - name: Install dependencies
        run:  bin/setup.sh
        shell: bash
      - name: compile
        run:  rake compile:byebug
      - name: test
        run:  |
          md temp
          $env:TMPDIR = "$env:GITHUB_WORKSPACE/temp"
          # Actions uses UTF8, causes test failures, similar to normal OS setup
          [Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("IBM437")
          [Console]::InputEncoding  = [System.Text.Encoding]::GetEncoding("IBM437")
          bundle exec rake test
